name: kitkonsult Feed
favicon: null
layout_spectrum: 0.24981
typography_spectrum: 0.901868186891079
title: 'KIT Konsult - Aligning business & IT - News feed'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0c4c8d'
    - '#689ac6'
    - '#7c9ebd'
    - '#9bb6cd'
  brandStrength: 0.7711298924405128
  lightness: 0.8936765887774527
  saturation: 0.09158165589906275
  rhythmicContrast: 0.4711248390376568
purpose: []
