name: kitkonsult Feed
favicon: null
layout_spectrum: 0.5958930347114801
typography_spectrum: 0.901868186891079
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7711298924405128
  lightness: 0.8936765887774527
  saturation: 0.09158165589906275
  rhythmicContrast: 0.4711248390376568
purpose: []
